[package]
name = "gameboy"
version = "0.1.0"
authors = ["tompko <tompko@gmail.com>"]

[dependencies]
clap = "2"
byteorder = "0.5"
time = "0.1"
rand = "0.3"
minifb = "0.9.0"
strfmt = "0.1.5"
combine = "2.3.1"
